desc_list = {
    "DISCOVER DES:E-PAYMENT": "DISCOVER: PAYMENT",
    "PUBLIC SERVICE DES:PSEG": "PSEG: PAYMENT",
    "VENMO DES:PAYMENT": "VENMO: PAYMENT",
    "VENMO DES:CASHOUT": "VENMO: CASHOUT",
    "PANERA, LLC DES:PAYROLL": "PANERA: PAYROLL",
    "UBER USA 6787 DES:EDI PAYMNT": "UBER: PAYROLL",
    "DoorDash, Inc. DES:DoorDash": "DoorDash: PAYROLL",
    "BKOFAMERICA ATM": "ATM: DEPOSIT",
    "VANGUARD BUY DES:INVESTMENT": "VANGAURD: PURCAHSE",
    "TREASURY DIRECT DES:TREAS": "I-BONDS: PURCHASE",
    "COSTCO": "COSTCO: PURCHASE",
    "WAL-MART": "WAL-MART: PURCHASE",
    "TARGET": "TARGET: PURCHASE"
}
